name: Build
on:
  release:
    types:
        - created

jobs:
  release:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64win, arm64win, amd64mac, arm64mac]
        include:
          - platform: amd64mac
            runner: macos-15-intel
          - platform: arm64mac
            runner: macos-latest
          - platform: amd64win
            runner: windows-latest
          - platform: arm64win
            runner: windows-11-arm

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: install dependencies
      run: npm ci

    - name: compile
      run: npm run compile

    - name: build
      run: npm run build

    - name: publish
      run: npm run publish
  
  release-linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64lin, arm64lin]
        include:
          - platform: amd64lin
            runner: ubuntu-latest
          - platform: arm64lin
            runner: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: install flatpak build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder elfutils
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: install snapcraft
      run: |
        sudo snap install snapcraft --classic --channel=7.x/stable



    - name: install dependencies
      run: npm ci

    - name: compile
      run: npm run compile

    - name: build
      run: npm run build
    
    - name: publish
      run: npm run publish
    env:
        SNAPCRAFT_BUILD_ENVIRONMENT: host